#!/bin/bash
cd $1
. commandline < input > output.out 2> output.err
diff output.out expected.out
if [ ! $? -eq 0 ]; then
 echo "FAILURE: $1"
 exit 1
fi
diff output.err expected.err
if [ ! $? -eq 0 ]; then
 echo "FAILURE: $1" 
 exit 1
fi
rm output.out
rm output.err
